config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  resources :categories
  resources :purchases

  root 'pages#home'

  get 'profile' => 'pages#profile'

  get 'dashboard' => 'purchases#dashboard'

  if Rails.env.development?
  	mount LetterOpenerWeb::Engine, at:"/letter_opener"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div class="container-fluid" id="productsContainer">
  <div class="row-fluid">
    <div class="col-md-2" id="categories">
      <h3 class="text-center">Categorías</h3>
      <ul class="list-group">
        <% @categories.each do |category| %>
        <li class="list-group-item"><%= link_to category.name, root_path(category_id: category.id) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-10">
      <% if @products.size > 0 %>
      <% @products.each do |product| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <div class="price btn-primary"> <%= number_to_currency(product.price,preicios: 0)%></div>
          <%= image_tag product.image.url(:thumb), class: 'image-responsive' %>
          <div class="caption">
            <h3><%= product.name %></h3>
            <p class="description"><%= product.description %></p>
            <p><%= link_to 'Comprar', purchases_path(product_id: product.id), method: :post,class: 'btn btn-primary btn-large' %></p>
          </div>
        </div>
      </div>
      <% end %>
      <% else %>
      <h2 class="text-center">No hay productos en esta categoría</h2>
      <% end %>

    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @user.email %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h1>Compras por pagar</h1>
      <table class="table text-center">
        <thead>
          <th class="text-center">Imagen</th>
          <th class="text-center">Producto</th>
          <th class="text-center">Precio</th>
          <th class="text-center">Fecha</th>
          <th class="text-center">Estado</th>
          <% if current_user.admin? %>
            <th>Opciones</th>
          <% end %>
        </thead>
        <tbody>
            <% @pending_purchases.each do |purchase| %>
            <tr>
              <td><%= image_tag purchase.product.image.url(:micro_thumb)%></td>
              <td><%= purchase.product.name %></td>
              <td><%= purchase.product.price %></td>
              <td><%= purchase.product.created_at.strftime("Comprado el %d de %B de %Y") %></td>
              <td class="danger"><%= purchase.status.humanize %></td>
              <% if current_user.admin? %>
                <td><%= link_to 'Pagar', purchase_path(id: purchase.id, user_id: purchase.user_id), method: :patch %> -
                    <%= link_to 'Eliminar', purchase_path(id: purchase.id, user_id: purchase.user_id), method: :delete, data: {confirm: "Seguro que deseas elimiar esta compra?"} %>
                </td>
              <% end %>
            </tr>
            <% end %>

            <% @paid_purchases.each do |purchase| %>
            <tr>
              <td><%= image_tag purchase.product.image.url(:micro_thumb)%></td>
              <td><%= purchase.product.name %></td>
              <td><%= purchase.product.price %></td>
              <td><%= purchase.product.created_at.strftime("Comprado el %d de %B de %Y") %></td>
              <td class="success"><%= purchase.status.humanize %></td>
              <% if current_user.admin? %>
                <td><%= link_to 'Eliminar', purchase_path(id: purchase.id, user_id: purchase.user_id), method: :delete, data: {confirm: "Seguro que deseas elimiar esta compra?"} %></td>
              <% end %>
            </tr>
            <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>